"""add planner_core tables

Revision ID: 7e3a98542cc5
Revises: aedc5d4d9d3b
Create Date: 2026-03-15 03:15:42.864014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3a98542cc5'
down_revision: Union[str, Sequence[str], None] = 'aedc5d4d9d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("money_maker", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_members",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("1"),
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money_maker', schema=None) as batch_op:
        batch_op.drop_column('is_members')

    # ### end Alembic commands ###
